# Generated by Django 3.2 on 2023-11-23 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20231122_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria'),
            preserve_default=False,
        ),
    ]
