# Generated by Django 3.2 on 2023-11-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20231123_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
