# Generated by Django 3.2 on 2023-11-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_categoria_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]

